<a href="https://colab.research.google.com/github/bchabros/machine_learning_bootcamp/blob/main/supervised/02_linear_regression/01_linear_regression_normal_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [5]:
X1 = X1.reshape(m, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [6]:
bias = np.ones((m,1))
print(bias)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [7]:
X = np.append(bias, X1, axis=1)
print(X)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]


Równanie normalne

In [8]:
np.dot(X.T, X)

array([[ 6., 21.],
       [21., 91.]])

In [10]:
L = np.linalg.inv(np.dot(X.T, X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [11]:
P = np.dot(X.T, Y)
P

array([21750., 80500.])

In [12]:
np.dot(L, P)

array([2750.,  250.])

Końcowa postać modelu Y = 2750 + 250X_1

SICKIT-LEARN

In [15]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1, Y)

print(regression.intercept_)
print(regression.coef_)

2750.0
[250.]
